package com.wolfeleo2.thingy.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

// Amber palette — mapped from the PRD §2.1 role table (seed #e6a23c).
// Fully populated with all 30+ Material 3 roles to avoid the default purple fallbacks.
val AmberLightColors = lightColorScheme(
    primary = Color(0xFFE6A23C),
    onPrimary = Color(0xFF2B2418),
    primaryContainer = Color(0xFFF7E8CD),
    onPrimaryContainer = Color(0xFF9A6416),
    inversePrimary = Color(0xFFF0C078),
    secondary = Color(0xFF8D8271),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFF3ECDD),
    onSecondaryContainer = Color(0xFF2B2418),
    tertiary = Color(0xFFB5AA97),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFECE3D1),
    onTertiaryContainer = Color(0xFF2B2418),
    background = Color(0xFFFAF6EE),
    onBackground = Color(0xFF2B2418),
    surface = Color(0xFFFFFDF8),
    onSurface = Color(0xFF2B2418),
    surfaceVariant = Color(0xFFF3ECDD),
    onSurfaceVariant = Color(0xFF8D8271),
    surfaceTint = Color(0xFFE6A23C),
    inverseSurface = Color(0xFF231E16),
    inverseOnSurface = Color(0xFFF4EDDD),
    error = Color(0xFFC05A3A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF410002),
    outline = Color(0xFFB5AA97),
    outlineVariant = Color(0xFFECE3D1),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFFFFFDF8),
    surfaceDim = Color(0xFFE7DECB),
    surfaceContainerLowest = Color(0xFFFFFDF8),
    surfaceContainerLow = Color(0xFFFBF6EC),
    surfaceContainer = Color(0xFFF3ECDD),
    surfaceContainerHigh = Color(0xFFEDE5D3),
    surfaceContainerHighest = Color(0xFFE7DECB),
)

val AmberDarkColors = darkColorScheme(
    primary = Color(0xFFE6A23C),
    onPrimary = Color(0xFF2B2418),
    primaryContainer = Color(0xFF3A2F1C),
    onPrimaryContainer = Color(0xFFF0C078),
    inversePrimary = Color(0xFFE6A23C),
    secondary = Color(0xFFA2977F),
    onSecondary = Color(0xFF2B2418),
    secondaryContainer = Color(0xFF2C261C),
    onSecondaryContainer = Color(0xFFF4EDDD),
    tertiary = Color(0xFF6F6650),
    onTertiary = Color(0xFF2B2418),
    tertiaryContainer = Color(0xFF332C20),
    onTertiaryContainer = Color(0xFFF4EDDD),
    background = Color(0xFF191510),
    onBackground = Color(0xFFF4EDDD),
    surface = Color(0xFF231E16),
    onSurface = Color(0xFFF4EDDD),
    surfaceVariant = Color(0xFF2C261C),
    onSurfaceVariant = Color(0xFFA2977F),
    surfaceTint = Color(0xFFE6A23C),
    inverseSurface = Color(0xFFFFFDF8),
    inverseOnSurface = Color(0xFF2B2418),
    error = Color(0xFFE07A58),
    onError = Color(0xFF2B2418),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    outline = Color(0xFF6F6650),
    outlineVariant = Color(0xFF332C20),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFF362F23),
    surfaceDim = Color(0xFF141009),
    surfaceContainerLowest = Color(0xFF141009),
    surfaceContainerLow = Color(0xFF1E1911),
    surfaceContainer = Color(0xFF231E16),
    surfaceContainerHigh = Color(0xFF2C261C),
    surfaceContainerHighest = Color(0xFF362F23),
)
